### ISSUE TITLE
Watch it icons

### ISSUE THREAD

**Issue by jyrgen112** [markheinmets/Grupp-4#10]
Icons for watch it.

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/f5f4b532-1ed7-4177-aafe-9be0d7eb45ec)

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/6c86fce0-5e6f-442b-b18e-7c633a678032)

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/e0aae18b-ee92-41d8-9a10-9397458e4b5c)

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/2e1a4b2d-c867-4fa6-b280-3f5f2a3b0696)

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/b8286031-b577-4e6b-b1f8-abb09db63d46)

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/b703f76d-d8b7-4c89-ab3d-2b24ac4921a8)

**Comment by D1ZEASE420** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/98657402/319609c6-eb5c-47c1-bc06-e3cac617af4e)

**Comment by D1ZEASE420** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/98657402/737a4453-0cf0-4b79-ac3a-62ac80047fb4)

**Comment by D1ZEASE420** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/98657402/12f74c31-1e7a-4b08-8e36-66b6ba07c77f)

**Comment by D1ZEASE420** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/98657402/9a8fd5bb-480a-43a1-8b7c-c1651cec77ff)

**Comment by jyrgen112** [comment]
netflix: https://www.netflix.com/ee/
Google play: https://play.google.com/store/movies/details/The_Dark_Knight?id=5svF9XxTZa8.P&hl=en&gl=US
Apple tv: https://tv.apple.com/us/movie/the-dark-knight/umc.cmc.1uf4c3neuc9yxhnjv7t4rd5wa
Amazon: https://www.amazon.com/Dark-Knight-Christian-Bale/dp/B0B6PKFVHR
