### ISSUE TITLE
Gallery

### ISSUE THREAD

**Issue by mariakallaste** [markheinmets/Grupp-4#12]
https://www.warnerbros.com/movies/dark-knight#gallery

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/bd8ebe51-99d8-4f14-8c83-c656c5623767)

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/25e288f4-7884-4d2b-8f98-41446dc7ed22)

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/7e4b2b55-6deb-4ab8-9bad-070f624cce66)

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/eff4affd-5d49-497f-82b3-4a43556b08b2)

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/097a7ae7-13be-4ab8-9526-0f003b23fc7a)

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/b81e530d-11a9-4480-ac33-b24c5bf4abb8)

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/6b16c947-8d7d-4fb4-bcdb-ea6796612364)

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/d3bba056-049e-4b92-a621-197f7a2f3216)

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/37ef3eb7-98f7-4bda-8d32-cf9a995b6488)

**Comment by jyrgen112** [comment]
![image](https://github.com/markheinmets/Grupp-4/assets/145542702/2d0674ff-eb22-4cd7-9234-51c58856109d)
