### ISSUE TITLE
piltide otsimine 

### ISSUE THREAD

**Issue by 41r1** [markheinmets/Grupp-4#3]

**Comment by markheinmets** [comment]
![d030d491-7a4a-42aa-832f-b2fd25d5b1f8](https://github.com/markheinmets/Grupp-4/assets/144334247/24863495-cc37-4616-9ac5-5f61f8a02017)

**Comment by jyrgen112** [comment]
![dark-knight-rises-premiere](https://github.com/markheinmets/Grupp-4/assets/145542702/1bfcd3b9-b6ca-4209-a8e3-fe21e97b16b2)
